project:
  type: book

book:
  title: "Quarto skills presentation"
  author: "Ricardo"
  date: "7/29/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cyborg
  pdf:
    documentclass: scrreprt



